package io.lownoise.voxen.docker;

import io.lownoise.voxen.core.ProjectConfig;

import java.util.List;

public class DockerfileGenerator {

    private final BaseImageResolver resolver;

    public DockerfileGenerator() {
        this.resolver = new BaseImageResolver();
    }

    public DockerfileGenerator(BaseImageResolver resolver) {
        this.resolver = resolver;
    }

    public String generate(ProjectConfig config, BuildMetadata metadata) {
        BaseImageResolver.BaseImage base = resolver.resolve(config.runtime(), metadata.nativeImage());
        StringBuilder df = new StringBuilder();

        df.append("# Syntax: docker/dockerfile:1\n");
        df.append("# Generated by Voxen ").append(metadata.voxenVersion()).append("\n");
        df.append("# Build: ").append(metadata.buildId()).append("\n");
        df.append("# Timestamp: ").append(metadata.timestamp()).append("\n\n");

        if (metadata.needsBuildStage()) {
            String buildImage = metadata.buildImage() != null
                ? metadata.buildImage()
                : resolveBuildImage(config.runtime(), metadata.nativeImage());
            df.append("FROM ").append(buildImage).append(" AS builder\n");
            df.append("WORKDIR /build\n");
            df.append("COPY . .\n");
            df.append("RUN ").append(metadata.buildCommand()).append("\n\n");
        }

        df.append("FROM ").append(base.fullName()).append("\n");
        df.append("WORKDIR /app\n\n");

        List<String> labels = DockerLabeler.generateLabels(metadata, config);
        for (String label : labels) {
            df.append("LABEL ").append(label).append("\n");
        }
        df.append("\n");

        if (metadata.needsBuildStage()) {
            df.append("COPY --from=builder /build/")
              .append(metadata.artifactName()).append(" /app/")
              .append(metadata.artifactName()).append("\n");
        } else if (metadata.artifactName() != null) {
            df.append("COPY ").append(metadata.artifactName()).append(" /app/")
              .append(metadata.artifactName()).append("\n");
        }

        if (metadata.hasSbom()) {
            df.append("COPY bom.json /app/bom.json\n");
        }
        if (metadata.ascFile() != null) {
            df.append("COPY ").append(metadata.artifactName()).append(".asc /app/")
              .append(metadata.artifactName()).append(".asc\n");
        }

        if (metadata.nativeImage() && config.runtime().equalsIgnoreCase("java")) {
            df.append("COPY --from=builder /build/").append(config.name()).append(" /app/")
              .append(config.name()).append("\n");
        }

        if (metadata.createUser() && !base.image().contains("distroless")) {
            df.append("RUN addgroup -S app && adduser -S app -G app\n");
            df.append("USER app\n\n");
        }

        String entrypoint = resolveEntrypoint(config.runtime(), metadata);
        if (entrypoint != null) {
            df.append("ENTRYPOINT ").append(entrypoint).append("\n");
        }

        if (metadata.port() != null && !metadata.port().isBlank()) {
            df.append("EXPOSE ").append(metadata.port()).append("\n");
        }

        return df.toString();
    }

    private String resolveBuildImage(String runtime, boolean nativeImage) {
        return switch (runtime.toLowerCase()) {
            case "java", "kotlin" -> nativeImage
                ? "ghcr.io/graalvm/native-image:21-ol9"
                : "eclipse-temurin:21-jdk-alpine";
            case "node" -> "node:20-alpine";
            case "python" -> "python:3.11-slim";
            case "go" -> "golang:1.22-alpine";
            case "rust" -> "rust:1.77-slim-bookworm";
            case "dotnet" -> "mcr.microsoft.com/dotnet/sdk:8.0";
            default -> "debian:bookworm-slim";
        };
    }

    private String resolveEntrypoint(String runtime, BuildMetadata metadata) {
        if (metadata.nativeImage()) {
            return "[\"/app/" + metadata.projectName() + "\"]";
        }
        return switch (runtime.toLowerCase()) {
            case "java", "kotlin" -> "[\"java\", \"-jar\", \"/app/" + metadata.artifactName() + "\"]";
            case "node" -> "[\"node\", \"/app/" + metadata.artifactName() + "\"]";
            case "python" -> "[\"python\", \"/app/" + metadata.artifactName() + "\"]";
            case "go", "rust" -> "[\"/app/" + metadata.projectName() + "\"]";
            case "dotnet" -> "[\"dotnet\", \"/app/" + metadata.artifactName() + "\"]";
            default -> null;
        };
    }
}
