version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      junit:
        patterns:
          - "org.junit.*"
          - "org.junit.jupiter.*"
          - "org.junit.platform*"
      jackson:
        patterns:
          - "com.fasterxml.*"
      picocli:
        patterns:
          - "info.picocli*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
