Args = --enable-url-protocols=https \
        --enable-all-security-services \
        --no-fallback \
        --install-exit-handlers \
        -H:ReflectionConfigurationResources=META-INF/native-image/io.lownoise.voxen/cli/reflect-config.json
